[tools]
go = "1.25"
node = { version = "24.6.0", postinstall = "cd apispec && npm install" }

[tasks.server]
run = "go run cmd/server/server.go"

[tasks."generate:apispec"]
run = "npm run compile"
dir = "apispec"

[tasks.copyspec]
run = "cp apispec/tsp-output/schema/openapi.json ./service/openapi.json"
depends = ["generate:apispec"]

[tasks.generate]
run = "go generate ./..."
depends = ["copyspec"]
