// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// WidgetsAnalyze implements Widgets_analyze operation.
//
// Analyze a widget.
//
// POST /widgets/{id}/analyze
func (UnimplementedHandler) WidgetsAnalyze(ctx context.Context, params WidgetsAnalyzeParams) (r *AnalyzeResult, _ error) {
	return r, ht.ErrNotImplemented
}

// WidgetsCreate implements Widgets_create operation.
//
// Create a widget.
//
// POST /widgets
func (UnimplementedHandler) WidgetsCreate(ctx context.Context, req *WidgetCreateRequest) (r *Widget, _ error) {
	return r, ht.ErrNotImplemented
}

// WidgetsDelete implements Widgets_delete operation.
//
// Delete a widget.
//
// DELETE /widgets/{id}
func (UnimplementedHandler) WidgetsDelete(ctx context.Context, params WidgetsDeleteParams) error {
	return ht.ErrNotImplemented
}

// WidgetsList implements Widgets_list operation.
//
// List widgets.
//
// GET /widgets
func (UnimplementedHandler) WidgetsList(ctx context.Context) (r *WidgetList, _ error) {
	return r, ht.ErrNotImplemented
}

// WidgetsRead implements Widgets_read operation.
//
// Read widgets.
//
// GET /widgets/{id}
func (UnimplementedHandler) WidgetsRead(ctx context.Context, params WidgetsReadParams) (r *Widget, _ error) {
	return r, ht.ErrNotImplemented
}

// WidgetsUpdate implements Widgets_update operation.
//
// Update a widget.
//
// PATCH /widgets/{id}
func (UnimplementedHandler) WidgetsUpdate(ctx context.Context, req *WidgetUpdateRequest, params WidgetsUpdateParams) (r *Widget, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
