// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	WidgetsAnalyzeOperation OperationName = "WidgetsAnalyze"
	WidgetsCreateOperation  OperationName = "WidgetsCreate"
	WidgetsDeleteOperation  OperationName = "WidgetsDelete"
	WidgetsListOperation    OperationName = "WidgetsList"
	WidgetsReadOperation    OperationName = "WidgetsRead"
	WidgetsUpdateOperation  OperationName = "WidgetsUpdate"
)
